### ISSUE TITLE
Getting some errors with Rushti 1.4

### ISSUE THREAD

**Issue by atifxhameed** [cubewise-code/rushti#81]
Hi, I am getting the following errors with RushTi 1.4. Same with 1.3. With 1.2 the process runs but not multithreaded. Am i doing some wrong. Please advise. Thank you

E:\rushti>python RushTI.py Tasks.txt 4
Traceback (most recent call last):
  File "E:\rushti\RushTI.py", line 829, in <module>
    tm1_service_by_instance = setup_tm1_services(maximum_workers, tasks_file_path, execution_mode)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\rushti\RushTI.py", line 92, in setup_tm1_services
    tm1_instances_in_tasks = get_instances_from_tasks_file(execution_mode, max_workers, tasks_file_path)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\rushti\RushTI.py", line 145, in get_instances_from_tasks_file
    tasks = get_ordered_tasks_and_waits(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\rushti\RushTI.py", line 466, in get_ordered_tasks_and_waits
    return extract_ordered_tasks_and_waits_from_file_type_norm(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\rushti\RushTI.py", line 271, in extract_ordered_tasks_and_waits_from_file_type_norm
    original_tasks = [extract_task_or_wait_from_line(line) for line in file.readlines() if not line.startswith('#')]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\rushti\RushTI.py", line 189, in extract_task_or_wait_from_line
    instance_name=line_arguments.pop("instance"),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'instance'

**Comment by MariusWirtz** [comment]
Your line in the `tasks` file misses the `instance` argument

**Comment by atifxhameed** [comment]
Thanks for the help Marius. I was able to fix the instance issue. Now the process runs but it does not use multiple threads. It just runs as a normal process with one thread. Is this due to a Tm1 setting ?
